version: '3.0'
services:
  db:
    container_name: qr-db
    image: postgres:14
    hostname: db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    restart: always
    networks:
      default:
        aliases:
          - 'db.sandbox'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_USER=postgres

  # turborepo
  api:
    container_name: qr-app
    hostname: app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
    networks:
      default:
        aliases:
          - 'app.sandbox'
    restart: always

networks:
  turbo-network:
    driver: bridge
volumes:
  db_data:
