import '../../styles/privacy.css';

import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'next-i18next/pages';

const Home: NextPage = () => {
  const { t } = useTranslation('homeScreen');
  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <iframe src="/privacy-html.html" width="100%" height="100%" />
    </>
  );
};

export default Home;
