import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'react-i18next';

import Learn from '../../components/Learn';

const Home: NextPage = () => {
  const { t } = useTranslation('homeScreen');
  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Learn />
    </>
  );
};

export default Home;
