import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import LandingPage from '../components/LandingPage'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Menu-go</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <LandingPage />
      </Layout>
    </>
  )
}

export default Home
