import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'react-i18next';

// import Layout from '../components/Layout'
// import LandingPage from '../components/LandingPage'
import Landing from '../components/Landing';

const Home: NextPage = () => {
  const { t } = useTranslation('homeScreen');
  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
};

export default Home;
