import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'next-i18next';

import Login from '../../components/Login';

const Home: NextPage = () => {
  const { t } = useTranslation('homeScreen');
  return (
    <>
      <Head>
        <title>{t('login')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </>
  );
};

export default Home;
